config/routes.rb
Bootstrap3::Application.routes.draw do
  resources :turds
  root 'turds#index'

  

end

app/models/turd.rb
class Turd < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/turds_controller.rb
class TurdsController < ApplicationController
  before_action :set_turd, only: [:show, :edit, :update, :destroy]

  # GET /turds
  # GET /turds.json
  def index
    @turds = Turd.all
  end

  # GET /turds/1
  # GET /turds/1.json
  def show
  end

  # GET /turds/new
  def new
    @turd = Turd.new
  end

  # GET /turds/1/edit
  def edit
  end

  # POST /turds
  # POST /turds.json
  def create
    @turd = Turd.new(turd_params)

    respond_to do |format|
      if @turd.save
        format.html { redirect_to @turd, notice: 'Turd was successfully created.' }
        format.json { render action: 'show', status: :created, location: @turd }
      else
        format.html { render action: 'new' }
        format.json { render json: @turd.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /turds/1
  # PATCH/PUT /turds/1.json
  def update
    respond_to do |format|
      if @turd.update(turd_params)
        format.html { redirect_to @turd, notice: 'Turd was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @turd.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /turds/1
  # DELETE /turds/1.json
  def destroy
    @turd.destroy
    respond_to do |format|
      format.html { redirect_to turds_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_turd
      @turd = Turd.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def turd_params
      params[:turd]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/turds_helper.rb
module TurdsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bootstrap3</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a href="#" class="navbar-brand">Bootswatch</a>
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar-main">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="http://builtwithbootstrap.com/" target="_blank">Built With Bootstrap</a></li>
        <li><a href="https://wrapbootstrap.com/?ref=bsw" target="_blank">WrapBootstrap</a></li>
      </ul>
    </div>
  </div>
</div>
<%= yield %>

</body>
</html>

app/views/turds/_form.html.erb
<%= form_for(@turd) do |f| %>
  <% if @turd.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@turd.errors.count, "error") %> prohibited this turd from being saved:</h2>

      <ul>
      <% @turd.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/turds/edit.html.erb
<h1>Editing turd</h1>

<%= render 'form' %>

<%= link_to 'Show', @turd %> |
<%= link_to 'Back', turds_path %>

app/views/turds/index.html.erb
<h1>Listing turds</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @turds.each do |turd| %>
      <tr>
        <td><%= link_to 'Show', turd %></td>
        <td><%= link_to 'Edit', edit_turd_path(turd) %></td>
        <td><%= link_to 'Destroy', turd, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Turd', new_turd_path %>

app/views/turds/new.html.erb
<h1>New turd</h1>

<%= render 'form' %>

<%= link_to 'Back', turds_path %>

app/views/turds/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_turd_path(@turd) %> |
<%= link_to 'Back', turds_path %>